In [1]:
# inbuilt module to create an array in python called array module
# array definition?:=> a collection which contain similar type of data type called array 


In [2]:
import array

In [4]:
a=array.array("I",[1,2,3,4,5])

In [6]:
print(a)

array('I', [1, 2, 3, 4, 5])


In [7]:
print(type(a))

<class 'array.array'>


In [8]:
a=array.array("I",[1,2,3,4,5,"krishna"])

TypeError: 'str' object cannot be interpreted as an integer

In [9]:
a=array.array("I",[1,2,3,4,5,"10"])

TypeError: 'str' object cannot be interpreted as an integer

In [10]:
# c++
# numpy module

In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy

In [15]:
a=numpy.array([1,2,3,4,5])

In [16]:
print(a)

[1 2 3 4 5]


In [17]:
a=numpy.array([1,2,3,4,"krishna"])

In [19]:
print(a)

['1' '2' '3' '4' 'krishna']


In [21]:
b=numpy.array([1,2,3,4,10.0])

In [22]:
print(b)

[ 1.  2.  3.  4. 10.]


In [26]:
c=numpy.array([1,2,3,4,"10"],dtype=numpy.int8)

In [27]:
print(c)

[ 1  2  3  4 10]


In [37]:
d=numpy.array([1,2,3,4,"10.0"],dtype=numpy.float16)

In [38]:
print(d)

[ 1.  2.  3.  4. 10.]


In [39]:
numpy.array(d,dtype=numpy.int8)

array([ 1,  2,  3,  4, 10], dtype=int8)